server:
  port: 9002

management:
   endpoints:
     web:
       base-path: "/olx-advertise-monitor"
       exposure:
         include: "*"
   health:
     circuitbreakers:
       enabled: true
   endpoint:
     health:
       show-details: always

spring:
  application:
    name: advertise-service
  config:
    import: configserver:http://localhost:9999
  zipkin:
    base-url: http://localhost:9411

resilience4j:
  circuitbreaker:
    instances:
      ALL-CATEGORIES-CIRCUIT_BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreashold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
      CATEGORY-CIRCUIT_BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreashold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
      ALL-STATUS-CIRCUIT_BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreashold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
      STATUS-CIRCUIT_BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreashold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
      USERNAME-CIRCUIT_BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreashold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
      VALIDATE-TOKEN-CIRCUIT_BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreashold: 50
        minimumNumberOfCalls: 2
        permittedNumberOfCallsInHalfOpenState: 1
        waitDurationInOpenState: 5s