server:
  port: 9002

management:
   endpoints:
     web:
       base-path: "/olx-advertise-monitor"
       exposure:
         include: "*"

spring:
  application:
    name: advertise-service
  datasource:
    url: jdbc:mysql://localhost:3306/olx
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true